In [15]:
[x for x in range(10) if x%2==1]

[1, 3, 5, 7, 9]

In [16]:
[x*2+1 for x in range(5)]

[1, 3, 5, 7, 9]

In [20]:
list(map(lambda x: x**2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [22]:
a_list = [(6, 2), (1, 5), (2, 3), (4, 1), (5, 2), (1, 3)]
sorted(a_list,key=lambda x: x[0]+x[1])

[(1, 3), (2, 3), (4, 1), (1, 5), (5, 2), (6, 2)]

In [26]:
a_list = [(6, 2), (1, 5), (2, 3), (4, 1), (5, 2), (1, 3)]
a_list.sort(key=lambda x: x[0]+x[1])
a_list

[(1, 3), (2, 3), (4, 1), (1, 5), (5, 2), (6, 2)]

In [34]:
a_list = [7, 2, 3, 4, 5, 6, 1]
a_list.index(4)

3

In [38]:
# CONJUNTOS Y LISTAS

frutas={'manzana','pera','piña','lulo','manzana','mora','pera','fresa','maracuya'}
frutas #elementos de conjunto sin repetir

{'fresa', 'lulo', 'manzana', 'maracuya', 'mora', 'pera', 'piña'}

In [39]:
'pera' in frutas

True

In [40]:
'aguacate' in frutas

False

In [44]:
a=set('abracadabra')
a

{'a', 'b', 'c', 'd', 'r'}

In [45]:
b=set('alacazam')
b

{'a', 'c', 'l', 'm', 'z'}

In [46]:
a-b #letras de a pero no en b

{'b', 'd', 'r'}

In [47]:
b-a #letras de b pero no en a

{'l', 'm', 'z'}

In [51]:
a|b # con junto union a + b

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [55]:
a & b # conjuno interseccion

{'a', 'c'}

In [56]:
a^b # a + b menos la interseccion 

{'b', 'd', 'l', 'm', 'r', 'z'}

In [59]:
# matrices

import numpy as np

matrisA=np.array([[1,2,3,4],[3,4,8,3],[9,4,8,23],[4,6,22,53]])
print('matrisA =', matrisA)

matrisB=np.array([[7,33,45,8],[3,4,8,2],[23,14,5,67],[44,6,2,35]])
print('matrisB =', matrisB)

matrisA = [[ 1  2  3  4]
 [ 3  4  8  3]
 [ 9  4  8 23]
 [ 4  6 22 53]]
matrisB = [[ 7 33 45  8]
 [ 3  4  8  2]
 [23 14  5 67]
 [44  6  2 35]]


In [60]:
# suma de matrices
suma=matrisA+matrisB
print(suma)

[[ 8 35 48 12]
 [ 6  8 16  5]
 [32 18 13 90]
 [48 12 24 88]]


In [61]:
# suma de matrices
suma=matrisA-matrisB
print(suma)

[[ -6 -31 -42  -4]
 [  0   0   0   1]
 [-14 -10   3 -44]
 [-40   0  20  18]]


In [62]:
# multiplicacion de matrices
multipli=np.dot(matrisA,matrisB)
print(multipli)

[[ 258  107   84  353]
 [ 349  245  213  673]
 [1271  563  523 1421]
 [2884  782  444 3373]]


In [64]:
A=np.linalg.det(matrisA)
print(A)

2203.9999999999973


In [65]:
np.trace(matrisA)

66

In [100]:
M = [[1, 2, 3],
    [1, 3, 2],
    [3, 1, 2]]
M[2][1] 

1

In [67]:
# vectrores
import numpy as np
a=np.array([2,3,4])
bm=np.array([[2,5,1],[5,6,3],[8,9,2]])
a

array([2, 3, 4])

In [68]:
bm

array([[2, 5, 1],
       [5, 6, 3],
       [8, 9, 2]])

In [69]:
# size nos permite conocer el numero de elmentos en el arre
print("Num. elementos en a", a.size) 

Num. elementos en a 3


In [70]:
print("Num. elementos en a", bm.size)

Num. elementos en a 9


In [72]:
import numpy as np

TempC=[12.10, 10.1, 13.15, 13.00, 17.9, 30.8, 18.88, 16, 20.2, 34.90]
arregloTemp=np.array(TempC)
print(arregloTemp)
# par cambiar a todos loe elementos del arreglo
# para cambiar a kelvin
print(arregloTemp+273.15)

[12.1  10.1  13.15 13.   17.9  30.8  18.88 16.   20.2  34.9 ]
[285.25 283.25 286.3  286.15 291.05 303.95 292.03 289.15 293.35 308.05]


In [ ]:

t=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12])
for i in range(0,12):
  print('valor anterios:', t[i+1])
  t[i+1]=t[i+1]*2
  print('valor actual: ', t[i+1])


In [74]:
a = {1, 2, 3, 4, 5}
b = {3, 7, 8, 9, 1}
a^b

{2, 4, 5, 7, 8, 9}

In [78]:
set([1,2,3])

{1, 2, 3}

In [99]:
a_set = set('manzana')
a_set
'man' is not a_set

True